## Agrégation des $B$-splines par la médiane:

Permet de rendre les résultats plus interprétables pour la visualisation des classifications, etc. ...

In [27]:
#install.packages("tidyverse")

In [28]:
library("caret")
library("corrplot")
library("corrr")
library("CVglasso")
library("dplyr")
library("e1071")
library("fda")
library("ggplot2")
library("glasso")
library("igraph")
library("mclust")
library("nnet")
library("pls")
library("qgraph")
library("randomForest")
library("readr")
library("splines")
library("tidymodels")
library("tidyverse")
library("VGAM")
library("xgboost")

In [29]:
df_new <- read.csv('../../pipeline_2/data/multispec_bsplines_IGT.csv', row.names = 'X')
head(df_new)

                   bspline_1_1  bspline_2_1 bspline_3_1 bspline_4_1 bspline_5_1
1-2Dichloroethane0  0.042859950  0.31041698  0.51403305  0.62173780 0.03431683
1-2Dichloroethane1  0.006455640  0.39251760  0.82991897  0.26948011 0.54668293
1-2Dichloroethane2  0.327938158 -0.26464513  0.48451374  0.02351809 0.04324316
1-chlorodecane0    -0.001266327  0.02122973 -0.01433533  0.03552926 0.01566774
4-octylphenol0      0.191932261 -0.28559929  0.46884036 -0.46132427 2.32348311
4-octylphenol1      0.191932261 -0.28559929  0.46884036 -0.46132427 2.32348311
                   bspline_6_1 bspline_7_1 bspline_8_1 bspline_9_1 bspline_1_2
1-2Dichloroethane0 -0.31216163 -0.16177808 -0.61811774 -0.69611517  0.319171851
1-2Dichloroethane1  0.24931517 -0.63373810  0.46927073 -0.33824607 -0.015799672
1-2Dichloroethane2  0.11916632  0.08827694  0.02312422  0.02278163  0.354224106
1-chlorodecane0     0.01169483  0.06060685  0.07095725  0.02065529  0.007125068
4-octylphenol0      0.61417648  1.78721517 -0.47782508  0.94929057 -0.054622886
4-octylphenol1      0.61417648  1.78721517 -0.47782508  0.94929057  0.068498536
                   ⋯ bspline_9_2 bspline_1_3 bspline_2_3 bspline_3_3
1-2Dichloroethane0 ⋯  0.25465136  0.17421335 -0.29096780  0.45766335
1-2Dichloroethane1 ⋯  0.04691594 -0.03380804  0.05718799 -0.09338539
1-2Dichloroethane2 ⋯ -0.34282508  0.15004945 -0.23951635  0.32780252
1-chlorodecane0    ⋯  0.02228604  0.00000000  0.00000000  0.00000000
4-octylphenol0     ⋯  1.79662924  0.08616678 -0.13326610  0.15897355
4-octylphenol1     ⋯  1.13125647  0.04647230 -0.09804601  0.20415663
                   bspline_4_3 bspline_5_3 bspline_6_3 bspline_7_3 bspline_8_3
1-2Dichloroethane0 -0.63651666 -0.6101915  -1.0122583  -0.7202593  -1.0490280
1-2Dichloroethane1  0.14276143 -0.8036310  -0.6387393  -0.6808124  -0.4320695
1-2Dichloroethane2 -0.31169849 -0.7677156  -0.7875300  -0.4524011  -0.7705458
1-chlorodecane0     0.00000000  0.0000000   0.0000000   0.0000000   0.0000000
4-octylphenol0     -0.03092931  0.1156325   0.3229518   0.1170611   0.9125265
4-octylphenol1      0.27047965  0.4234347   0.5865024   1.3926614   0.5701989
                   bspline_9_3
1-2Dichloroethane0 -0.8609281
1-2Dichloroethane1 -0.6110400
1-2Dichloroethane2 -0.3562878
1-chlorodecane0     0.0000000
4-octylphenol0      0.4000610
4-octylphenol1      0.9129696

In [30]:
## ajout col nom complet substance (filtrage plus simple pour groupage par sub via médiane):
df_name <- read.csv("../../../projet/pipeline_2/data/fPCA_score_agg_Default_IGT.csv", row.names = "Repetition")

In [31]:
df_name[30:40, ]

                X  fPC1        fPC2        fPC3         fPC4
Carbaryl0       29   0.2216584   4.5410169  -0.23979933  8.3694283
Carbaryl1       30   0.6141355   2.8307450   0.07181435  7.0509765
Chlorothanolil0 31  -4.2157692  -6.2185271 -14.11709524  1.7408734
Chlorothanolil1 32 -10.8082462   1.4887476  -5.34452726 -5.5619762
Chlorothanolil2 33  -8.0111422   8.1199191  -7.45544061 -1.5065235
Chlorpyrifos0   34   3.1473240   0.7937227   0.87630972  1.2636626
Chlorpyrifos1   35   5.7751258  -3.3695465  -0.30917356 -2.7363597
Cypermethrine0  36   8.2715743 -12.6919954   4.52968774 -9.5225959
Cypermethrine1  37  14.6116240 -12.8808631   4.32391859 -4.1544355
DDD(2-4)0       38   2.2002701   8.9722511  -6.89903107 -3.9547667
DDD(2-4)1       39   2.1447993   5.8287071  -1.90519442 -0.9349445
                sub_full       y
Carbaryl0       Carbaryl       1
Carbaryl1       Carbaryl       1
Chlorothanolil0 Chlorothalonil 3
Chlorothanolil1 Chlorothalonil 3
Chlorothanolil2 Chlorothalonil 3
Chlorpyrifos0   Chlorpyrifos   1
Chlorpyrifos1   Chlorpyrifos   1
Cypermethrine0  Cypermethrine  1
Cypermethrine1  Cypermethrine  1
DDD(2-4)0       DDD(2-4)       1
DDD(2-4)1       DDD(2-4)       1

In [32]:
rownames(df_name)[rownames(df_name) == "Chlorothanolil0"] <- "Chlorothalonil0"
rownames(df_name)[rownames(df_name) == "Chlorothanolil1"] <- "Chlorothalonil1"
rownames(df_name)[rownames(df_name) == "Chlorothanolil2"] <- "Chlorothalonil2"

In [33]:
df_name[30:40, ]

                X  fPC1        fPC2        fPC3         fPC4
Carbaryl0       29   0.2216584   4.5410169  -0.23979933  8.3694283
Carbaryl1       30   0.6141355   2.8307450   0.07181435  7.0509765
Chlorothalonil0 31  -4.2157692  -6.2185271 -14.11709524  1.7408734
Chlorothalonil1 32 -10.8082462   1.4887476  -5.34452726 -5.5619762
Chlorothalonil2 33  -8.0111422   8.1199191  -7.45544061 -1.5065235
Chlorpyrifos0   34   3.1473240   0.7937227   0.87630972  1.2636626
Chlorpyrifos1   35   5.7751258  -3.3695465  -0.30917356 -2.7363597
Cypermethrine0  36   8.2715743 -12.6919954   4.52968774 -9.5225959
Cypermethrine1  37  14.6116240 -12.8808631   4.32391859 -4.1544355
DDD(2-4)0       38   2.2002701   8.9722511  -6.89903107 -3.9547667
DDD(2-4)1       39   2.1447993   5.8287071  -1.90519442 -0.9349445
                sub_full       y
Carbaryl0       Carbaryl       1
Carbaryl1       Carbaryl       1
Chlorothalonil0 Chlorothalonil 3
Chlorothalonil1 Chlorothalonil 3
Chlorothalonil2 Chlorothalonil 3
Chlorpyrifos0   Chlorpyrifos   1
Chlorpyrifos1   Chlorpyrifos   1
Cypermethrine0  Cypermethrine  1
Cypermethrine1  Cypermethrine  1
DDD(2-4)0       DDD(2-4)       1
DDD(2-4)1       DDD(2-4)       1

In [34]:
df_new$full_name <- df_name$sub_full[match(rownames(df_new), rownames(df_name))]

In [35]:
## sanity check:
df_new

                      bspline_1_1   bspline_2_1   bspline_3_1   bspline_4_1
1-2Dichloroethane0     0.0428599502  0.3104169809  0.5140330488  0.6217378048
1-2Dichloroethane1     0.0064556398  0.3925176002  0.8299189711  0.2694801130
1-2Dichloroethane2     0.3279381580 -0.2646451337  0.4845137377  0.0235180885
1-chlorodecane0       -0.0012663269  0.0212297344 -0.0143353314  0.0355292603
4-octylphenol0         0.1919322615 -0.2855992927  0.4688403629 -0.4613242667
4-octylphenol1         0.1919322615 -0.2855992927  0.4688403629 -0.4613242667
124-Trichlorobenzene0  0.0080013122  0.0048791414  0.0135043987  0.0134059151
124-Trichlorobenzene1  0.0150202732  0.0208173917  0.0415044430  0.0180178136
A7360                 -0.0083587626  0.0129428213 -0.0122405416  0.0383206750
A7361                  0.0047421902 -0.0056120308  0.0089717414  0.0014654213
A7362                  0.0001266427 -0.0002040018  0.0002881707 -0.0003093356
Acetone0              -0.1037677172  0.2436964285 -0.2286078720  0.4595281512
Acide Acrylique0      -0.0138687686  0.0224506731 -0.0322218102  0.0362930814
Acide Acrylique2       0.0193533175 -0.0170341111  0.0081433786 -0.0014809858
alphaEndosulfan0      -0.0257425563  0.0414168643 -0.0582721574  0.0617663959
alphaEndosulfan1       0.0686174929  0.0729933322  0.0758895581 -0.0301569163
Anthracene0            0.0112833380 -0.0035387151  0.0042153649  0.0100615545
Anthracene1            0.0223243999  0.0443031921  0.0067911488  0.0534494792
Benzene0              -0.0032100417  0.0051140268 -0.0069609412  0.0065793351
Benzo(a)pyrene0        0.0062563039  0.0079999960  0.0051797947  0.0075225582
Benzo(a)pyrene1        0.0011393776  0.0116848390  0.0229642380  0.0068387836
betaEndosulfan0        0.1413728947  0.1457643275  0.0629026990  0.3157186454
betaEndosulfan1       -0.0494857894  0.1573128534 -0.1690678923  0.4834011094
Biphenyl0              0.0566832110  0.0018694659  0.0684699170  0.0370776260
Carbaryl0             -0.0040301059  0.0064913954 -0.0091674238  0.0098328736
Carbaryl1              0.0102989871  0.0154930753  0.0057310709  0.0182174427
Chlorothalonil0        0.3190079900 -0.4811450592  0.7959279702  0.3750572876
Chlorothalonil1       -0.0498051964  0.0504892546  0.4227561693  0.2827023467
Cypermethrine0         0.0060855316 -0.0058878657  0.0242972469  0.0014851482
Cypermethrine1         0.0383392487 -0.0448855071  0.0724580553 -0.0690505424
⋮                     ⋮             ⋮             ⋮             ⋮
Isodrin1              -0.0027426400  0.0159698089 -0.021821625   0.051867018
L10000                -0.0033674407  0.0054107985 -0.007580326   0.007925222
L10001                 0.0229778013 -0.0004923251  0.049069306   0.006531031
Lindane0               0.0251485057  0.0423187245  0.014097340   0.013413691
Methomyl0              0.0101283631 -0.0162784099  0.022824738  -0.023928633
Methomyl2              0.8748400647  1.0399102047  0.874644578   0.931712862
Methomyl3              0.7732457664  0.8350954611  1.248958113   0.144768001
Methomyl4             -0.0219703779  0.0354502221 -0.050350642   0.054972862
Methomyl5              0.0204572027  0.0114748610  0.002965137   0.037571475
Methomyl6              0.0224387593 -0.0361129545  0.050863143  -0.054095221
Nitric Acid0           0.0250425475  0.0243924276  0.737599512   0.500201254
Pentachlorophenol0     0.0203545897  0.0026650157  0.036063473  -0.011136610
Pentachlorophenol1     0.0533430747 -0.0252628315  0.132572910   0.058087087
PiperonylButoxide0    -0.2160782988  0.3697489099 -0.355960208   0.515195428
PiperonylButoxide1    -0.0631069995  0.1493583556 -0.066086701   0.311645287
Quinoxyfen0            0.1884852674  0.2449370092  0.591349371   0.500222184
Quinoxyfen2            0.0209928417  0.3119059175  0.299559768   0.063095388
Tebufenozide0         -0.0006292347  0.0010152783 -0.001441921   0.001573955
Tebufenozide1         -0.0004462748  0.0008195449 -0.001614385   0.003182741
Tetrachloroethylene0   0.1474406115 -0.2264531024  0.943257222   0.439936263
Tetrachloroethylene1   0.0359936512  0.5246422508  0.901533370   1.049709026
Trichloroethylene0     0.1858204426  0.3970895037  0.918473643   0.183399154
Trichloroethylene1     0.0198590359  0.7879306662  0.456602053   0.081418374
Trichloroethylene2     0.1313696112  0.9534556663  1.409151632   0.402883962
Trifluralin0           0.0710520193 -0.0729763682  0.093895380   0.222385266
Trifluralin2           0.0011127074  0.0203077811 -0.015404697   0.046317369
Trifluralin3           0.0000000000  0.0000000000  0.000000000   0.000000000
Verapamil0             0.0080529306  0.0017047815 -0.003793111   0.004809442
Verapamil1             0.0029918715 -0.0048203551  0.006813370  -0.007327616
Verapamil2             0.0063720373  0.0266331459 -0.014037008   0.018608411
                      bspline_5_1   bspline_6_1   bspline_7_1   bspline_8_1
1-2Dichloroethane0     0.0343168263 -0.3121616308 -0.1617780782 -0.6181177421
1-2Dichloroethane1     0.5466829256  0.2493151690 -0.6337381047  0.4692707261
1-2Dichloroethane2     0.0432431615  0.1191663208  0.0882769398  0.0231242212
1-chlorodecane0        0.0156677416  0.0116948309  0.0606068544  0.0709572486
4-octylphenol0         2.3234831092  0.6141764850  1.7872151736 -0.4778250813
4-octylphenol1         2.3234831092  0.6141764850  1.7872151736 -0.4778250813
124-Trichlorobenzene0  0.0004118712  0.0421897391 -0.0186243209  0.0045459801
124-Trichlorobenzene1  0.0556598030 -0.0632748582  0.0416242482  0.0182982485
A7360                  0.0023603288  0.0014072831 -0.0522923263 -0.0168930498
A7361                 -0.0009516024 -0.0067533222  0.0646195562 -0.0343015551
A7362                  0.0005435396 -0.0005483989  0.0014935253 -0.0008293828
Acetone0               0.2982836627  0.0379303268  0.1938724915 -0.0359831218
Acide Acrylique0      -0.0842066590  0.0030465803 -0.0230749327 -0.0678262034
Acide Acrylique2       0.0007624145 -0.0004793398  0.0003413712 -0.0001955210
alphaEndosulfan0      -0.0983080575 -0.0306370024  0.0078963991 -0.0252333473
alphaEndosulfan1       0.2267423852  0.0410824205 -0.0664998839 -0.1055469459
Anthracene0           -0.0051114224  0.0295783816  0.0101583369 -0.0549513619
Anthracene1            0.0307927283  0.0738296192  0.0130599175  0.0445412924
Benzene0               0.0009656230  0.0092986515  0.0102252733  0.0192412215
Benzo(a)pyrene0        0.0072171457 -0.0050593643  0.0098297776  0.0072627882
Benzo(a)pyrene1       -0.0041600649  0.0036512054  0.0148981626  0.0095010568
betaEndosulfan0        0.6843853710 -0.1425877237  0.1996506350 -0.0073481870
betaEndosulfan1        0.3484145768  0.1003224789 -0.0292954494  0.1297452407
Biphenyl0              0.0313608061 -0.0208829117  0.0663098685 -0.0133992818
Carbaryl0             -0.0171281779  0.0003299394  0.0023507948 -0.0040603461
Carbaryl1             -0.0091704863  0.0300679229  0.0047917082 -0.0054395489
Chlorothalonil0       -0.1636329692  0.1033441346 -0.1011521998  0.0796640156
Chlorothalonil1        0.4907750068  0.3588281681 -0.2784662925 -0.2270383331
Cypermethrine0        -0.0046423736 -0.0037381394  0.0955818506 -0.0122702002
Cypermethrine1         0.1579653570 -0.2885172404  0.7112342233  0.1341953654
⋮                     ⋮             ⋮             ⋮             ⋮
Isodrin1              -8.051748e-04  0.085822566  -0.045926138   0.210549485
L10000                -1.123851e-02  0.015011631   0.005838386  -0.225783060
L10001                 1.246567e-01 -0.222354721   0.970426346  -0.435917477
Lindane0               4.994126e-02  0.014989449  -0.009174572   0.005344027
Methomyl0              3.476260e-02  0.004105140  -1.097365061  -0.759832184
Methomyl2              2.554728e-01  0.036290132  -0.281285877  -1.002649743
Methomyl3              1.144830e+00 -0.442802322  -0.571079541  -1.134945646
Methomyl4             -1.085360e-01  0.234338628  -0.568805251  -0.889390317
Methomyl5             -2.486842e-02  0.135965285  -0.644394123  -0.679829646
Methomyl6              8.870385e-02 -0.074551366  -0.741172801  -0.895935379
Nitric Acid0           7.713636e-01  0.616640400   0.886250820  -0.125016250
Pentachlorophenol0     1.912390e-01 -0.024396286   0.171872921   0.004278293
Pentachlorophenol1     9.081840e-02  0.612988071  -0.273347017   0.226735437
PiperonylButoxide0     7.170607e-01 -0.217690376   0.437338166  -0.198937431
PiperonylButoxide1     2.403348e-02  0.102160819   0.116562476   0.067497673
Quinoxyfen0            8.794226e-02  0.342716176  -0.064127091   0.112513370
Quinoxyfen2            3.373153e-01  0.177139672   0.224366749  -0.066578858
Tebufenozide0         -3.102115e-03  0.006271976  -0.003034385   0.001358022
Tebufenozide1         -3.355435e-03  0.019039907  -0.001793824   0.048957697
Tetrachloroethylene0  -2.913444e-01  2.011416349  -0.436017699   0.755644962
Tetrachloroethylene1   1.026339e+00  0.948277907   0.973874899   1.002516732
Trichloroethylene0     6.037604e-03  0.186237423  -0.261693563   0.088388878
Trichloroethylene1    -2.585310e-02  0.089358804  -0.030008337   0.045769220
Trichloroethylene2     1.635160e-01 -0.011725360   0.330628547  -0.257650816
Trifluralin0           1.575317e-01  0.075247057  -0.016747866  -0.032138921
Trifluralin2          -6.504848e-02 -0.108581982  -0.604170329  -0.068591031
Trifluralin3           0.000000e+00  0.000000000   0.000000000   0.000000000
Verapamil0            -3.116481e-05  0.004624178   0.001597459  -0.001290675
Verapamil1             1.300259e-02  0.002180075  -0.002769583   0.001876100
Verapamil2             2.274004e-03  0.018013187   0.004070673   0.007439431
                      bspline_9_1   bspline_1_2   ⋯ bspline_1_3   bspline_2_3
1-2Dichloroethane0    -0.6961151714  0.3191718511 ⋯  0.1742133519 -0.290967797
1-2Dichloroethane1    -0.3382460723 -0.0157996724 ⋯ -0.0338080388  0.057187990
1-2Dichloroethane2     0.0227816304  0.3542241057 ⋯  0.1500494456 -0.239516349
1-chlorodecane0        0.0206552934  0.0071250680 ⋯  0.0000000000  0.000000000
4-octylphenol0         0.9492905666 -0.0546228864 ⋯  0.0861667801 -0.133266101
4-octylphenol1         0.9492905666  0.0684985358 ⋯  0.0464723011 -0.098046006
124-Trichlorobenzene0  0.0011581828  0.0820340491 ⋯  0.0023898678 -0.003857041
124-Trichlorobenzene1  0.0045270320 -0.1114213676 ⋯  0.1671736117  0.030992751
A7360                  0.0002765820  0.0489670559 ⋯ -0.0015143726  0.002437177
A7361                  0.0163372353  0.1388354413 ⋯  0.0000000000  0.000000000
A7362                  0.0002838245  0.0154097063 ⋯ -0.0541941677 -0.065246504
Acetone0               0.0639831126  0.0008141887 ⋯ -0.0158548049  0.025765823
Acide Acrylique0      -0.1136585207 -0.2484772004 ⋯  0.0000000000  0.000000000
Acide Acrylique2       0.0000707482 -0.1228108660 ⋯ -0.0018580680  0.002995866
alphaEndosulfan0       0.0090047854  0.1456984032 ⋯  0.0007039317 -0.001134623
alphaEndosulfan1       0.0792419335 -0.0006065600 ⋯ -0.0071958383 -0.341392613
Anthracene0            0.0141489642  0.1340556007 ⋯ -0.0029944741  0.004825585
Anthracene1            0.0353496470 -0.0709084713 ⋯  0.0261885113 -0.071220098
Benzene0               0.0124475315  0.0546834443 ⋯  0.0078233008 -0.003968894
Benzo(a)pyrene0        0.0067349222  0.0207521396 ⋯ -0.0333524927  0.052600428
Benzo(a)pyrene1       -0.0014585673  0.0137113571 ⋯ -0.0412267974  0.068239078
betaEndosulfan0        0.0802249613 -0.0009664508 ⋯  0.0034356479 -0.005507073
betaEndosulfan1       -0.0040337990  0.0189826624 ⋯  0.0000000000  0.000000000
Biphenyl0              0.0330664593  0.0825990393 ⋯  0.0000000000  0.000000000
Carbaryl0              0.0092208172  0.0095357944 ⋯  0.4751230332  0.479616663
Carbaryl1              0.0078778470 -0.0027265765 ⋯  0.1080242897 -0.174058572
Chlorothalonil0       -0.0279911412  0.0054955342 ⋯ -0.0059831939 -0.002220180
Chlorothalonil1       -0.1295867447  0.3320923657 ⋯ -0.0135027498  0.013878963
Cypermethrine0         0.1360033416 -0.2677384638 ⋯ -0.0021729011  0.003502704
Cypermethrine1         0.1527364413  0.1380391259 ⋯ -0.0542807084  0.124389521
⋮                     ⋮             ⋮             ⋱ ⋮             ⋮
Isodrin1              -0.0509841914 -0.1194168324 ⋯  0.0000000000  0.000000000
L10000                 0.1040694606  0.0977701700 ⋯ -0.0207721404  0.033508128
L10001                 0.2594747449  0.2813706596 ⋯  0.0979210924 -0.152957706
Lindane0              -0.0019657156 -0.0510133867 ⋯ -0.0325757994  0.052235562
Methomyl0             -0.8984594338 -0.0030479022 ⋯ -0.0044168047  0.003783544
Methomyl2             -0.7695798504  0.0551178739 ⋯ -0.0019432649  0.003134396
Methomyl3             -0.8187321896  0.0000000000 ⋯  0.0000000000  0.000000000
Methomyl4             -0.7556766037  0.0001990574 ⋯ -0.0012658253  0.002058464
Methomyl5             -0.8310738065  0.0000000000 ⋯  0.0000000000  0.000000000
Methomyl6             -0.5967806795 -0.0002281908 ⋯  0.0000000000  0.000000000
Nitric Acid0           0.7787844827  0.2417809850 ⋯  0.0000000000  0.000000000
Pentachlorophenol0     0.0079776306 -0.0038142080 ⋯  0.0000000000  0.000000000
Pentachlorophenol1     0.0502329743 -0.0038142080 ⋯  0.0007316771 -0.001208730
PiperonylButoxide0     0.3997220098  0.0109811311 ⋯  0.0000000000  0.000000000
PiperonylButoxide1     0.0473050426  0.6581537855 ⋯  0.0000000000  0.000000000
Quinoxyfen0            0.2010269107  0.6004623324 ⋯  0.4498235388  0.331121161
Quinoxyfen2            0.1086969929  1.1335321134 ⋯  0.1353169858 -0.211592117
Tebufenozide0         -0.0004368142 -0.0941246969 ⋯  0.0241323208 -0.039042748
Tebufenozide1          0.0484982151  0.0448554487 ⋯  0.0000000000  0.000000000
Tetrachloroethylene0   0.8035672761 -0.1296487384 ⋯  0.0000000000  0.000000000
Tetrachloroethylene1   1.1743884106  0.1168020339 ⋯  0.0264131318 -0.042580517
Trichloroethylene0    -0.0522641897  0.2606215873 ⋯  0.0090344835 -0.133725400
Trichloroethylene1     0.0142270025  0.1333181338 ⋯  0.0892733161  0.023204982
Trichloroethylene2    -0.1508197012  0.7068389236 ⋯  0.0793952745 -0.235632160
Trifluralin0          -0.1953438991  0.0000000000 ⋯  0.0099662316 -0.016060843
Trifluralin2          -0.1895143085  0.0000000000 ⋯  0.0027267851  0.200277020
Trifluralin3           0.0000000000  0.0011238067 ⋯ -0.0282177255  0.045433050
Verapamil0             0.0091886547 -0.0881723367 ⋯ -0.0271243681  0.042947146
Verapamil1            -0.0007191914 -0.0241039586 ⋯ -0.0184030570  0.029705987
Verapamil2             0.0037996858  0.0824450103 ⋯ -0.0008501332  0.001372025
                      bspline_3_3  bspline_4_3   bspline_5_3  bspline_6_3
1-2Dichloroethane0     0.457663353 -0.636516656  -0.610191538 -1.012258286
1-2Dichloroethane1    -0.093385392  0.142761434  -0.803631031 -0.638739310
1-2Dichloroethane2     0.327802521 -0.311698492  -0.767715644 -0.787530033
1-chlorodecane0        0.000000000  0.000000000   0.000000000  0.000000000
4-octylphenol0         0.158973553 -0.030929314   0.115632488  0.322951751
4-octylphenol1         0.204156632  0.270479648   0.423434660  0.586502351
124-Trichlorobenzene0  0.005482283 -0.005999139   0.012015410 -0.027034034
124-Trichlorobenzene1 -0.018535870  0.019734837   0.002392184 -0.041270413
A7360                 -0.003432376  0.003649616  -0.005972552  0.004682305
A7361                  0.000000000  0.000000000   0.000000000  0.000000000
A7362                 -0.216685843 -0.079676574   0.046306217 -0.029979019
Acetone0              -0.037440308  0.043701629  -0.120702916 -0.051736799
Acide Acrylique0       0.000000000  0.000000000   0.000000000  0.000000000
Acide Acrylique2      -0.004244886  0.004600380  -0.008652143  0.015874852
alphaEndosulfan0       0.001605982 -0.001734825   0.003191043 -0.005365418
alphaEndosulfan1      -0.423667978 -0.088111034  -0.301735310  0.227377301
Anthracene0           -0.006825569  0.007357167  -0.013307047  0.013608933
Anthracene1            0.196671909 -0.051377634   0.047219347  0.054706706
Benzene0              -0.034986972  0.042674736  -0.158554275  0.087981225
Benzo(a)pyrene0       -0.068872753  0.053044670   0.633069865 -0.163775910
Benzo(a)pyrene1       -0.104586115  0.137083294   0.022334797  0.049933513
betaEndosulfan0        0.007653527 -0.007792003   0.008261671  0.034106105
betaEndosulfan1        0.000000000  0.000000000   0.000000000  0.000000000
Biphenyl0              0.000000000  0.000000000   0.000000000  0.000000000
Carbaryl0              0.246416738  0.325778811   0.031035271 -0.029959001
Carbaryl1              0.243917880 -0.231202781   0.060672850 -0.060314034
Chlorothalonil0        0.064328003 -0.346362780   0.093867505  0.046097402
Chlorothalonil1        0.095246374 -0.044244914   0.258867534  0.085957903
Cypermethrine0        -0.004959411  0.005362554  -0.009927145  0.015901143
Cypermethrine1        -0.293772946  0.064234073  -0.040907793  0.056114202
⋮                     ⋮            ⋮             ⋮            ⋮
Isodrin1               0.000000000  0.0000000000  0.000000000  0.000000000
L10000                -0.047552211  0.0517831363 -0.100510843  0.194498397
L10001                 0.184287054  0.0165574744 -0.005691516 -0.007838250
Lindane0              -0.072646277  0.0737220250 -0.003124763 -0.002605941
Methomyl0              0.005556463  0.0067567347 -0.018504974  0.035054092
Methomyl2             -0.004446535  0.0048369345 -0.009325712  0.018681843
Methomyl3              0.000000000  0.0000000000  0.000000000  0.000000000
Methomyl4             -0.002997365  0.0035190049 -0.009964303  0.012577791
Methomyl5              0.000000000  0.0000000000  0.000000000  0.000000000
Methomyl6              0.000000000  0.0000000000  0.000000000  0.000000000
Nitric Acid0           0.000000000  0.0000000000  0.000000000  0.000000000
Pentachlorophenol0     0.000000000  0.0000000000  0.000000000  0.000000000
Pentachlorophenol1     0.001846480 -0.0024507653  0.010325887 -0.061592331
PiperonylButoxide0     0.000000000  0.0000000000  0.000000000  0.000000000
PiperonylButoxide1     0.000000000  0.0000000000  0.000000000  0.000000000
Quinoxyfen0            0.247377078  0.3679823324  0.516917123  1.364068782
Quinoxyfen2            0.261546071 -0.0679428743  0.219759405  0.073979086
Tebufenozide0          0.055932623 -0.0626681783  0.142838335 -0.090160864
Tebufenozide1          0.000000000  0.0000000000  0.000000000  0.000000000
Tetrachloroethylene0   0.000000000  0.0000000000  0.000000000  0.000000000
Tetrachloroethylene1   0.060301719 -0.0652501223  0.122003941 -0.405648409
Trichloroethylene0    -0.470255935 -0.5821746888 -0.599593678 -0.549846627
Trichloroethylene1     0.182433383  0.0006383653  0.185810096  0.203348101
Trichloroethylene2    -0.064811862 -0.7275427425 -0.351891551 -0.741062553
Trifluralin0           0.022718700 -0.0244928688  0.044386517 -0.054188394
Trifluralin2          -0.082262973  0.0833438639 -0.040407802  0.059657575
Trifluralin3          -0.064079603  0.0684527126 -0.115849095  0.030643323
Verapamil0            -0.057213075  0.0496764789  0.080409239 -0.042155867
Verapamil1            -0.042246374  0.0463066653 -0.093679614  0.204211544
Verapamil2            -0.001950080  0.0021336726 -0.004270118  0.009551736
                      bspline_7_3  bspline_8_3  bspline_9_3
1-2Dichloroethane0    -0.720259341 -1.049027966 -0.860928113
1-2Dichloroethane1    -0.680812425 -0.432069494 -0.611039982
1-2Dichloroethane2    -0.452401110 -0.770545783 -0.356287780
1-chlorodecane0        0.000000000  0.000000000  0.000000000
4-octylphenol0         0.117061066  0.912526483  0.400061044
4-octylphenol1         1.392661378  0.570198885  0.912969638
124-Trichlorobenzene0  0.069573587  0.131426491 -0.007837363
124-Trichlorobenzene1  0.195565456 -0.090925733  0.209472727
A7360                  0.027621433 -0.020727465  0.008075005
A7361                  0.000000000  0.000000000  0.000000000
A7362                  0.021518836 -0.012367118  0.004480931
Acetone0              -0.042685487 -0.120099244  0.066707120
Acide Acrylique0       0.000000000  0.000000000  0.000000000

In [36]:
## group substances by median to have only one obs per susbtance (makes some results 'easier' and more interpretable for our task):
behaviour_median <- df_new %>% 
  group_by(full_name) %>% 
  summarise(across(where(is.numeric), \(x) median(x, na.rm = TRUE))) %>% 
  column_to_rownames("full_name")

In [37]:
behaviour_median

                     bspline_1_1   bspline_2_1   bspline_3_1   bspline_4_1
1-2Dichloroethane     0.0428599502  0.3104169809  0.5140330488  0.269480113
1-chlorodecane       -0.0012663269  0.0212297344 -0.0143353314  0.035529260
124-Trichlorobenzene  0.0115107927  0.0128482665  0.0275044208  0.015711864
4-octylphenol         0.1919322615 -0.2855992927  0.4688403629 -0.461324267
A736                  0.0001266427 -0.0002040018  0.0002881707  0.001465421
Acetone              -0.1037677172  0.2436964285 -0.2286078720  0.459528151
Acide Acrylique       0.0027422745  0.0027082810 -0.0120392158  0.017406048
Anthracene            0.0168038689  0.0203822385  0.0055032569  0.031755517
Benzene              -0.0032100417  0.0051140268 -0.0069609412  0.006579335
Benzo(a)pyrene        0.0036978407  0.0098424175  0.0140720163  0.007180671
Biphenyl              0.0566832110  0.0018694659  0.0684699170  0.037077626
Carbaryl              0.0031344406  0.0109922354 -0.0017181765  0.014025158
Chlorothalonil        0.1346013968 -0.2153279023  0.6093420697  0.328879817
Cypermethrine         0.0222123902 -0.0253866864  0.0483776511 -0.033782697
DDD(2-4)              0.0048497397  0.0020741020  0.0053765521  0.035371554
Dicofol               0.0195762518  0.2822117674  0.1985779460  0.091318713
H40                   0.0263596619 -0.0228030677  0.0871586600 -0.005067140
Ibuprofen             0.0306563822 -0.0486580338  0.0755960182  0.018611654
Isodrin              -0.0004177189  0.0102510174 -0.0152218361  0.030739305
L1000                 0.0098051803  0.0024592367  0.0207444902  0.007228127
Lindane               0.0251485057  0.0423187245  0.0140973405  0.013413691
Methomyl              0.0214479810  0.0234625416  0.0368439406  0.046272169
Nitric Acid           0.0250425475  0.0243924276  0.7375995120  0.500201254
Pentachlorophenol     0.0368488322 -0.0112989079  0.0843181914  0.023475238
PiperonylButoxide    -0.1395926492  0.2595536328 -0.2110234549  0.413420357
Quinoxyfen            0.1047390546  0.2784214634  0.4454545695  0.281658786
Tebufenozide         -0.0005377548  0.0009174116 -0.0015281530  0.002378348
Tetrachloroethylene   0.0917171314  0.1490945742  0.9223952958  0.744822645
Trichloroethylene     0.1313696112  0.7879306662  0.9184736435  0.183399154
Trifluralin           0.0011127074  0.0000000000  0.0000000000  0.046317369
Verapamil             0.0063720373  0.0017047815 -0.0037931114  0.004809442
alphaEndosulfan       0.0214374683  0.0572050983  0.0088087003  0.015804740
betaEndosulfan        0.0459435526  0.1515385905 -0.0530825967  0.399559877
                     bspline_5_1   bspline_6_1   bspline_7_1  bspline_8_1
1-2Dichloroethane     0.0432431615  0.1191663208 -0.161778078  0.023124221
1-chlorodecane        0.0156677416  0.0116948309  0.060606854  0.070957249
124-Trichlorobenzene  0.0280358371 -0.0105425596  0.011499964  0.011422114
4-octylphenol         2.3234831092  0.6141764850  1.787215174 -0.477825081
A736                  0.0005435396 -0.0005483989  0.001493525 -0.016893050
Acetone               0.2982836627  0.0379303268  0.193872492 -0.035983122
Acide Acrylique      -0.0417221223  0.0012836202 -0.011366781 -0.034010862
Anthracene            0.0128406529  0.0517040004  0.011609127 -0.005205035
Benzene               0.0009656230  0.0092986515  0.010225273  0.019241221
Benzo(a)pyrene        0.0015285404 -0.0007040794  0.012363970  0.008381922
Biphenyl              0.0313608061 -0.0208829117  0.066309868 -0.013399282
Carbaryl             -0.0131493321  0.0151989312  0.003571251 -0.004749948
Chlorothalonil        0.1635710188  0.2310861514 -0.189809246 -0.073687159
Cypermethrine         0.0766614917 -0.1461276899  0.403408037  0.060962583
DDD(2-4)              0.0155633957  0.0093377901  0.018709115  0.013761022
Dicofol               0.2846929798 -0.0684886787  0.119280414 -0.024946376
H40                   0.1784671482 -0.1464917088  0.026787162 -0.341204213
Ibuprofen            -0.0795727262  0.1669783008  0.105057645 -0.032982656
Isodrin              -0.0061921353  0.0270439619 -0.006599887  0.107720599
L1000                 0.0567091053 -0.1036715452  0.488132366 -0.330850268
Lindane               0.0499412567  0.0149894491 -0.009174572  0.005344027
Methomyl              0.0617332259  0.0201976358 -0.607736832 -0.892662848
Nitric Acid           0.7713636354  0.6166404001  0.886250820 -0.125016250
Pentachlorophenol     0.1410286746  0.2942958923 -0.050737048  0.115506865
PiperonylButoxide     0.3705470658 -0.0577647782  0.276950321 -0.065719879
Quinoxyfen            0.2126287998  0.2599279242  0.080119829  0.022967256
Tebufenozide         -0.0032287754  0.0126559410 -0.002414104  0.025157860
Tetrachloroethylene   0.3674971601  1.4798471279  0.268928600  0.879080847
Trichloroethylene     0.0060376045  0.0893588038 -0.030008337  0.045769220
Trifluralin           0.0000000000  0.0000000000 -0.016747866 -0.032138921
Verapamil             0.0022740038  0.0046241779  0.001597459  0.001876100
alphaEndosulfan       0.0642171638  0.0052227090 -0.029301742 -0.065390147
betaEndosulfan        0.5163999739 -0.0211326224  0.085177593  0.061198527
                     bspline_9_1   bspline_1_2   ⋯ bspline_9_2  bspline_1_3
1-2Dichloroethane    -0.3382460723  0.3191718511 ⋯  0.046915940  0.1500494456
1-chlorodecane        0.0206552934  0.0071250680 ⋯  0.022286039  0.0000000000
124-Trichlorobenzene  0.0028426074 -0.0146936592 ⋯  0.004155809  0.0847817398
4-octylphenol         0.9492905666  0.0069378247 ⋯  1.463942855  0.0663195406
A736                  0.0002838245  0.0489670559 ⋯  0.004387048 -0.0015143726
Acetone               0.0639831126  0.0008141887 ⋯ -0.006512883 -0.0158548049
Acide Acrylique      -0.0567938863 -0.1856440332 ⋯ -0.156064299 -0.0009290340
Anthracene            0.0247493056  0.0315735647 ⋯  0.017014074  0.0115970186
Benzene               0.0124475315  0.0546834443 ⋯ -0.099576610  0.0078233008
Benzo(a)pyrene        0.0026381774  0.0172317483 ⋯  0.048891946 -0.0372896450
Biphenyl              0.0330664593  0.0825990393 ⋯  0.009418177  0.0000000000
Carbaryl              0.0085493321  0.0034046089 ⋯  0.049262980  0.2915736614
Chlorothalonil       -0.0787889430  0.1687939499 ⋯ -0.058095409 -0.0097429718
Cypermethrine         0.1443698914 -0.0648496690 ⋯ -0.758429445 -0.0282268048
DDD(2-4)              0.0102476481  0.0731000207 ⋯  1.182605551  0.2959394143
Dicofol               0.0742280713 -0.0429044992 ⋯  0.069069441 -0.0157877142
H40                  -0.0587512714 -0.0542327056 ⋯  0.527446957  0.1736479742
Ibuprofen             0.0689017285  0.0001450938 ⋯  0.000913484 -0.0111957668
Isodrin              -0.0245151739 -0.1140039270 ⋯ -0.908640572  0.0000000000
L1000                 0.1817721027  0.1895704148 ⋯  0.050276299  0.0385744760
Lindane              -0.0019657156 -0.0510133867 ⋯ -0.621382126 -0.0325757994
Methomyl             -0.7941560200  0.0000000000 ⋯  0.000000000 -0.0006329126
Nitric Acid           0.7787844827  0.2417809850 ⋯  0.021631090  0.0000000000
Pentachlorophenol     0.0291053025 -0.0038142080 ⋯  0.013858862  0.0003658385
PiperonylButoxide     0.2235135262  0.3345674583 ⋯  0.017442700  0.0000000000
Quinoxyfen            0.1548619518  0.8669972229 ⋯  0.542427543  0.2925702623
Tebufenozide          0.0240307005 -0.0246346241 ⋯  0.008310403  0.0120661604
Tetrachloroethylene   0.9889778434 -0.0064233522 ⋯ -0.559495983  0.0132065659
Trichloroethylene    -0.0522641897  0.2606215873 ⋯ -0.112540196  0.0793952745
Trifluralin          -0.1895143085  0.0000000000 ⋯  0.000000000  0.0027267851
Verapamil             0.0037996858 -0.0241039586 ⋯  0.155308105 -0.0184030570
alphaEndosulfan       0.0441233595  0.0725459216 ⋯  0.106007584 -0.0032459533
betaEndosulfan        0.0380955811  0.0090081058 ⋯  0.052723971  0.0017178240
                     bspline_2_3   bspline_3_3   bspline_4_3  bspline_5_3
1-2Dichloroethane    -0.2395163495  0.3278025205 -0.311698492 -0.767715644
1-chlorodecane        0.0000000000  0.0000000000  0.000000000  0.000000000
124-Trichlorobenzene  0.0135678547 -0.0065267937  0.006867849  0.007203797
4-octylphenol        -0.1156560535  0.1815650921  0.119775167  0.269533574
A736                  0.0000000000 -0.0034323761  0.000000000  0.000000000
Acetone               0.0257658226 -0.0374403080  0.043701629 -0.120702916
Acide Acrylique       0.0014979329 -0.0021224431  0.002300190 -0.004326072
Anthracene           -0.0331972565  0.0949231698 -0.022010234  0.016956150
Benzene              -0.0039688936 -0.0349869721  0.042674736 -0.158554275
Benzo(a)pyrene        0.0604197534 -0.0867294341  0.095063982  0.327702331
Biphenyl              0.0000000000  0.0000000000  0.000000000  0.000000000
Carbaryl              0.1527790452  0.2451673087  0.047288015  0.045854060
Chlorothalonil        0.0058293914  0.0797871882 -0.195303847  0.176367519
Cypermethrine         0.0639461126 -0.1493661789  0.034798314 -0.025417469
DDD(2-4)              0.6542884905  0.2574875427  1.262588176  0.530517480
Dicofol               0.1474080002 -0.0411280009 -0.109588621  0.067662289
H40                  -0.1539600043 -0.0040683839 -0.257933570  0.009464201
Ibuprofen             0.0180417174 -0.0255180867  0.027501086 -0.049556653
Isodrin               0.0000000000  0.0000000000  0.000000000  0.000000000
L1000                -0.0597247889  0.0683674216  0.034170305 -0.053101179
Lindane               0.0522355623 -0.0726462768  0.073722025 -0.003124763
Methomyl              0.0010292319  0.0000000000  0.001759502 -0.004662856
Nitric Acid           0.0000000000  0.0000000000  0.000000000  0.000000000
Pentachlorophenol    -0.0006043651  0.0009232401 -0.001225383  0.005162943
PiperonylButoxide     0.0000000000  0.0000000000  0.000000000  0.000000000
Quinoxyfen            0.0597645223  0.2544615744  0.150019729  0.368338264
Tebufenozide         -0.0195213741  0.0279663114 -0.031334089  0.071419167
Tetrachloroethylene  -0.0212902585  0.0301508597 -0.032625061  0.061001971
Trichloroethylene    -0.1337253996 -0.0648118619 -0.582174689 -0.351891551
Trifluralin           0.0454330498 -0.0640796028  0.068452713 -0.040407802
Verapamil             0.0297059866 -0.0422463739  0.046306665 -0.004270118
alphaEndosulfan      -0.1712636182 -0.2110309980 -0.044922929 -0.149272133
betaEndosulfan       -0.0027535364  0.0038267633 -0.003896002  0.004130836
                     bspline_6_3  bspline_7_3   bspline_8_3   bspline_9_3
1-2Dichloroethane    -0.787530033 -0.6808124247 -7.705458e-01 -0.6110399816
1-chlorodecane        0.000000000  0.0000000000  0.000000e+00  0.0000000000
124-Trichlorobenzene -0.034152224  0.1325695214  2.025038e-02  0.1008176821
4-octylphenol         0.454727051  0.7548612223  7.413627e-01  0.6565153412
A736                  0.000000000  0.0215188361 -1.236712e-02  0.0044809306
Acetone              -0.051736799 -0.0426854873 -1.200992e-01  0.0667071195
Acide Acrylique       0.007937426 -0.0134205484  1.950719e-02  0.0177113287
Anthracene            0.034157819  0.0818012303  4.424704e-01  0.3242820970
Benzene               0.087981225 -0.0599329844  3.363773e-02 -0.0120739767
Benzo(a)pyrene       -0.056921199  0.0527243298  4.555126e-03 -0.0054489881
Biphenyl              0.000000000  0.0000000000  0.000000e+00  0.0000000000
Carbaryl             -0.045136518  0.0369032703 -5.597949e-03  0.0450638363
Chlorothalonil        0.066027653  0.1020117604  2.249489e-01 -0.1705518784
Cypermethrine         0.036007672 -0.0803410980  2.577500e-02  0.0123441301
DDD(2-4)              0.533736261  0.6075422459  4.230974e-01  0.4089252281
Dicofol               0.087416280  0.0897265007 -2.474002e-02  0.0585387454
H40                   0.489021872  0.3505996800  2.738079e-01  0.2458071416
Ibuprofen             0.007528689 -0.0015196611 -7.627063e-05  0.0001607391
Isodrin               0.000000000  0.0000000000  0.000000e+00  0.0000000000
L1000                 0.093330074 -0.0243994455  2.365977e-02 -0.0098810252
Lindane              -0.002605941  0.0027108604 -1.765721e-03  0.0006689857
Methomyl              0.006288895 -0.0087095725  8.192574e-03  0.0016539408
Nitric Acid           0.000000000  0.0000000000  0.000000e+00  0.0000000000
Pentachlorophenol    -0.030796166  0.2039007504 -3.768079e-02  0.0026183597
PiperonylButoxide     0.000000000  0.0000000000  0.000000e+00  0.0000000000
Quinoxyfen            0.719023934  0.5794935412  3.837801e-01  0.6890801446
Tebufenozide         -0.045080432  0.1857195313  7.208693e-02  0.0394294474
Tetrachloroethylene  -0.202824204 -0.0006827105 -8.759801e-02 -0.0980743665
Trichloroethylene    -0.549846627 -0.4284345362 -1.960619e-01 -0.2159737754
Trifluralin           0.030643323  0.0623234040  1.214066e-01  0.0122281260
Verapamil             0.009551736 -0.0234382179  1.314619e-02  0.0059785547
alphaEndosulfan       0.111005942 -0.2027647597  5.961917e-03  0.0132082315
betaEndosulfan        0.017053052 -0.2234366083 -1.176318e-01 -0.1526417182

In [38]:
write.csv(behaviour_median, "../data/multispec_bsplines_median_agreg2_IGT.csv")